/*
 * Copyright (C) 2025 moi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gcodeeditor.gui;

import gcodeeditor.GRBLControler;
import gcodeeditor.GRBLControler.GRBLCommListennerAdapter;
import javax.swing.SwingUtilities;

/**
 *
 * @author moi
 */
public class JGRBLInfoDialog extends javax.swing.JDialog {

    GRBLControler grbl;

    public JGRBLInfoDialog(java.awt.Frame parent, GRBLControler grbl0, boolean modal) {
        super(parent, modal);
        grbl = grbl0;        
        initComponents();
        
        grbl.addListenner(new GRBLCommListennerAdapter() { 
                                @Override
                                public void stateChanged() { updateGUI(); }
                                });
        SwingUtilities.invokeLater( () -> { updateGUI(); } );
    }
    
    public void updateGUI() {
        jLabelConnected.setText( grbl.isConnected() ? "Yes" : "No");
        jLabelMachineName.setText( grbl.getMachineName());
        jLabelGRBLVersion.setText( grbl.getVersion());
        jLabelGRBLOPT.setText(grbl.getOPT());
        jLabelTLO.setText(grbl.getTLO());
        jLabelPRB.setText(grbl.getPRB());
        jLabelGC.setText( grbl.getGC());
        jTextAreaOffsets.setText( "Working Coordinates Offsets\n\n" + grbl.getWCOs());
        this.revalidate();
        this.repaint();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMachine = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabelConnected = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMachineName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelGRBLVersion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelGRBLOPT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTLO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelPRB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelGC = new javax.swing.JLabel();
        jPanelOffset = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOffsets = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setTitle("GRBL Informations");

        jPanelMachine.setLayout(new java.awt.GridLayout(7, 0, 5, 5));

        jLabel11.setText("Connected");
        jPanelMachine.add(jLabel11);

        jLabelConnected.setText("no");
        jPanelMachine.add(jLabelConnected);

        jLabel1.setText("Name");
        jPanelMachine.add(jLabel1);

        jLabelMachineName.setText("<unknow>");
        jPanelMachine.add(jLabelMachineName);

        jLabel5.setText("GRBL Version");
        jPanelMachine.add(jLabel5);

        jLabelGRBLVersion.setText("ver");
        jPanelMachine.add(jLabelGRBLVersion);

        jLabel2.setText("Options [OPT]");
        jPanelMachine.add(jLabel2);

        jLabelGRBLOPT.setText("opt");
        jPanelMachine.add(jLabelGRBLOPT);

        jLabel3.setText("Tool len [TLO]");
        jPanelMachine.add(jLabel3);

        jLabelTLO.setText("tlo");
        jPanelMachine.add(jLabelTLO);

        jLabel6.setText("Probe [PRB]");
        jPanelMachine.add(jLabel6);

        jLabelPRB.setText("prb");
        jPanelMachine.add(jLabelPRB);

        jLabel9.setText("Context [GC]");
        jPanelMachine.add(jLabel9);

        jLabelGC.setText("gc");
        jPanelMachine.add(jLabelGC);

        jTabbedPane1.addTab("Machine", jPanelMachine);

        jTextAreaOffsets.setEditable(false);
        jTextAreaOffsets.setColumns(20);
        jTextAreaOffsets.setRows(13);
        jScrollPane1.setViewportView(jTextAreaOffsets);

        jPanelOffset.add(jScrollPane1);

        jTabbedPane1.addTab("Offsets", jPanelOffset);

        jPanel1.add(jTabbedPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConnected;
    private javax.swing.JLabel jLabelGC;
    private javax.swing.JLabel jLabelGRBLOPT;
    private javax.swing.JLabel jLabelGRBLVersion;
    private javax.swing.JLabel jLabelMachineName;
    private javax.swing.JLabel jLabelPRB;
    private javax.swing.JLabel jLabelTLO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMachine;
    private javax.swing.JPanel jPanelOffset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaOffsets;
    // End of variables declaration//GEN-END:variables

    private class GRBLCommListennerAdapterImpl extends GRBLControler.GRBLCommListennerAdapter {

        public GRBLCommListennerAdapterImpl() {
        }

        @Override
        public void wPosChanged() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void stateChanged() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void settingsReady() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void receivedError(int errono, String line) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void receivedAlarm(int alarmno) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void receivedMessage(String substring) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void accessoryStateChanged() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void feedSpindleChanged() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void sendedLine(String cmd) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void receivedLine(String l) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void overrideChanged() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void exceptionInGRBLComThread(Exception ex) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void probFinished(String substring) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void limitSwitchChanged() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
