/*
 * Copyright (C) 2019 Clément Gérardin @ Marseille.fr
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed serialReader the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have receivedLine a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gcodeeditor.gui;

import gcodeeditor.GWord;
import gcodeeditor.GRBLControler;
import java.text.DecimalFormat;
import java.util.Locale;
import javax.swing.JTextField;

/**
 * A frame that allow to JOG gantry with GRBL.
 * @author Clément
 */
public class JJoGFrame extends javax.swing.JFrame {

    /**
     * Creates new form JJoGFrame
     */
    
    public static final DecimalFormat NUM_FORMAT;
    static {
        NUM_FORMAT = (DecimalFormat)DecimalFormat.getInstance(Locale.ROOT);
        NUM_FORMAT.applyLocalizedPattern("########.####");
    }
    
    GRBLControler grbl;
    
    public JJoGFrame( GRBLControler grbl) {
        this.grbl = grbl;
        initComponents();        
        jComboBoxDistance.setSelectedIndex(4);
        updatePositions();
        grbl.addListenner(new GRBLControler.GRBLCommListennerInterface() {
            @Override
            public void wPosChanged() {
                updatePositions();
            }
            @Override
            public void stateChanged() { 
                updatePositions();
            }
            @Override
            public void receivedError(int errono, String line) { }
            @Override
            public void receivedAlarm(int alarmno) { }
            @Override
            public void accessoryStateChanged() { }
            @Override
            public void feedSpindleChanged() { }
            @Override
            public void sendedLine(String cmd) { }
            @Override
            public void receivedLine(String l) { }
            @Override
            public void overrideChanged() { }
            @Override
            public void receivedMessage(String substring) { }
            @Override
            public void exceptionInGRBLComThread(Exception ex) { }
            @Override
            public void settingsReady() { }
            @Override
            public void probFinished(String substring) { }
            @Override
            public void limitSwitchChanged() { }
        });
    }
    
    final void updatePositions() {
        if ( ! grbl.isConnected()) return;
        if ( grbl.isSettingsReady() ) {
            jCheckBoxShowLaser.setEnabled( grbl.isLaserMode());
            jButtonHome.setEnabled(grbl.canHome());
        } else
            jCheckBoxShowLaser.setEnabled( false);
        
        if ( grbl.getParserStateStr() != null)
            jCheckBoxShowLaser.setSelected( ! grbl.getParserStateStr().contains("G0") && ! grbl.getParserStateStr().contains("S0"));
            
        if ( grbl.getMPos() != null) {
            jTextFieldMx.setText(NUM_FORMAT.format(grbl.getMPos().getX()));
            jTextFieldMy.setText(NUM_FORMAT.format(grbl.getMPos().getY()));
            jTextFieldMz.setText(NUM_FORMAT.format(grbl.getMPos().getZ()));
        }
        if ( grbl.getWPos() != null) {
            jTextFieldWx.setText(NUM_FORMAT.format(grbl.getWPos().getX()));
            jTextFieldWy.setText(NUM_FORMAT.format(grbl.getWPos().getY()));
            jTextFieldWz.setText(NUM_FORMAT.format(grbl.getWPos().getZ()));
        }
        
        if ( grbl.getState() == grbl.GRBL_STATE_HOLD) {
            jButtonHoldResume.setText("Resume");
        } else {
            jButtonHoldResume.setText("HOLD");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPrecision = new javax.swing.JPanel();
        jComboBoxDistance = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonMul10 = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonDiv10 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxShowLaser = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jButtonHoldResume = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelCoordValues = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldWx = new javax.swing.JTextField();
        jTextFieldWy = new javax.swing.JTextField();
        jTextFieldWz = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMx = new javax.swing.JTextField();
        jTextFieldMy = new javax.swing.JTextField();
        jTextFieldMz = new javax.swing.JTextField();
        jButtonW0 = new javax.swing.JButton();
        jButtonX0 = new javax.swing.JButton();
        jButtonY0 = new javax.swing.JButton();
        jButtonZ0 = new javax.swing.JButton();
        jPanelJogButtons = new javax.swing.JPanel();
        jButtonUL = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonUR = new javax.swing.JButton();
        jButtonTop = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonDL = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonDR = new javax.swing.JButton();
        jButtonBottom = new javax.swing.JButton();

        setTitle("GRBL JOG Window");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelPrecision.setLayout(new java.awt.GridBagLayout());

        jComboBoxDistance.setEditable(true);
        jComboBoxDistance.setMaximumRowCount(6);
        jComboBoxDistance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.001", "0.01", "0.1", "1", "10", "100" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelPrecision.add(jComboBoxDistance, gridBagConstraints);
        jPanelPrecision.add(jLabel1, new java.awt.GridBagConstraints());

        jButtonMul10.setText(" x10 ");
        jButtonMul10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMul10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMul10);

        jButtonPlus.setText("  + ");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPlus);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPrecision.add(jPanel3, gridBagConstraints);

        jButtonDiv10.setText(" ÷10 ");
        jButtonDiv10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiv10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonDiv10);

        jButtonMinus.setText("  -  ");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonMinus);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPrecision.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(jPanelPrecision, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("STOP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(jButton1, gridBagConstraints);

        jCheckBoxShowLaser.setText("Show laser (spindle=1)");
        jCheckBoxShowLaser.setEnabled(false);
        jCheckBoxShowLaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowLaserActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxShowLaser);

        jLabel5.setText("     ");
        jPanel1.add(jLabel5);

        jButtonHome.setText("HOME");
        jButtonHome.setEnabled(false);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);

        jButtonHoldResume.setText("Resume");
        jButtonHoldResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHoldResumeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHoldResume);

        jLabel4.setText("                      ");
        jPanel1.add(jLabel4);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClose);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jPanelCoordValues.setEnabled(false);
        jPanelCoordValues.setLayout(new java.awt.GridLayout(0, 4));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WPos :");
        jPanelCoordValues.add(jLabel2);

        jTextFieldWx.setFont(new java.awt.Font("DejaVu Sans", 1, 17)); // NOI18N
        jTextFieldWx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWxActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jTextFieldWx);

        jTextFieldWy.setFont(new java.awt.Font("DejaVu Sans", 1, 17)); // NOI18N
        jTextFieldWy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWyActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jTextFieldWy);

        jTextFieldWz.setFont(new java.awt.Font("DejaVu Sans", 1, 17)); // NOI18N
        jTextFieldWz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWzActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jTextFieldWz);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MPos :");
        jPanelCoordValues.add(jLabel3);

        jTextFieldMx.setColumns(7);
        jTextFieldMx.setFont(new java.awt.Font("DejaVu Sans", 1, 17)); // NOI18N
        jPanelCoordValues.add(jTextFieldMx);

        jTextFieldMy.setFont(new java.awt.Font("DejaVu Sans", 1, 17)); // NOI18N
        jTextFieldMy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMyActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jTextFieldMy);

        jTextFieldMz.setFont(new java.awt.Font("DejaVu Sans", 1, 17)); // NOI18N
        jPanelCoordValues.add(jTextFieldMz);

        jButtonW0.setText("W=0");
        jButtonW0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonW0ActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jButtonW0);

        jButtonX0.setText("X=0");
        jButtonX0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX0ActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jButtonX0);

        jButtonY0.setText("Y=0");
        jButtonY0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonY0ActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jButtonY0);

        jButtonZ0.setText("Z=0");
        jButtonZ0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZ0ActionPerformed(evt);
            }
        });
        jPanelCoordValues.add(jButtonZ0);

        jPanel2.add(jPanelCoordValues);

        jPanelJogButtons.setEnabled(false);
        jPanelJogButtons.setLayout(new java.awt.GridLayout(0, 4));

        jButtonUL.setText("    ");
        jButtonUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonULActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonUL);

        jButtonU.setText("North");
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonU);

        jButtonUR.setText("    ");
        jButtonUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonURActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonUR);

        jButtonTop.setText("Up");
        jButtonTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTopActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonTop);

        jButtonL.setText("Left");
        jButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonL);

        jButtonH.setText("Zero");
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonH);

        jButtonR.setText("Right");
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonR);

        jLabel6.setText(" ");
        jPanelJogButtons.add(jLabel6);

        jButtonDL.setText("    ");
        jButtonDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDLActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonDL);

        jButtonD.setText("South");
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonD);

        jButtonDR.setText("    ");
        jButtonDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDRActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonDR);

        jButtonBottom.setText("Down");
        jButtonBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBottomActionPerformed(evt);
            }
        });
        jPanelJogButtons.add(jButtonBottom);

        jPanel2.add(jPanelJogButtons);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLActionPerformed
        jog(-1,0, 0);
    }//GEN-LAST:event_jButtonLActionPerformed

    private void jButtonMul10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMul10ActionPerformed
        Object o = jComboBoxDistance.getEditor().getEditorComponent();
        if ( o instanceof JTextField) {
            String val = ((JTextField) o).getText();
            try {
                double d = Double.valueOf(val);
                if ( d < 1000)
                ((JTextField) o).setText(NUM_FORMAT.format( (d * 10)));
            }
            catch (NumberFormatException e) { }
        }
    }//GEN-LAST:event_jButtonMul10ActionPerformed

    private void jButtonDiv10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiv10ActionPerformed
        Object o = jComboBoxDistance.getEditor().getEditorComponent();
        if ( o instanceof JTextField) {
            String val = ((JTextField) o).getText();
            try {
                double d = Double.valueOf(val);
                if ( d > 0.0001)
                ((JTextField) o).setText(NUM_FORMAT.format((d / 10)));
            }
            catch (NumberFormatException e) { }
        }
    }//GEN-LAST:event_jButtonDiv10ActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        Object o = jComboBoxDistance.getEditor().getEditorComponent();
        if ( o instanceof JTextField) {
            String val = ((JTextField) o).getText();
            try {
                double d = Double.valueOf(val);
                int m = 0;
                if ( d > 1) {
                    while( d >= 10) { m++; d /= 10; }
                    //d = Math.pow(10,m) * (((int)d)+1);
                } else if (  Math.abs(d) > 0.0000001 )
                    while( d < 1) { m--; d *= 10; }
                
                if ( (int)d == 9) { d = 0; m++; }
                ((JTextField) o).setText(NUM_FORMAT.format(Math.pow(10,m) * (((int)(d+0.00001))+1)));
            }
            catch (NumberFormatException e) { }
        }
    }//GEN-LAST:event_jButtonPlusActionPerformed
        
    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        Object o = jComboBoxDistance.getEditor().getEditorComponent();
        if ( o instanceof JTextField) {
            String val = ((JTextField) o).getText();
            try {
                double d = Double.valueOf(val);
                int m = 0;
                if ( d > 1) {
                    while( d >= 10) { 
                        m++; d /= 10;
                    }
                    //d = Math.pow(10,m) * (((int)d)+1);
                } else if ( Math.abs(d) > 0.0000001 )
                        while( d < 1) { 
                            m--; d *= 10;
                        }
                
                if ( (int)d == 1) { d = 10; m --;}
                ((JTextField) o).setText(NUM_FORMAT.format(Math.pow(10,m) * (((int)(d+0.00001))-1)));
            }
            catch (NumberFormatException e) { }
        }
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonULActionPerformed
        jog(-1,1, 0);
    }//GEN-LAST:event_jButtonULActionPerformed

    private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed
        jog(0, 1, 0);
    }//GEN-LAST:event_jButtonUActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        if ( grbl.isConnected()) grbl.jogCancel();
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonURActionPerformed
        jog(1,1, 0);
    }//GEN-LAST:event_jButtonURActionPerformed

    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        grbl.pushCmd("$J=X0Y0F5000");
    }//GEN-LAST:event_jButtonHActionPerformed

    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
        jog(1,0, 0);
    }//GEN-LAST:event_jButtonRActionPerformed

    private void jButtonDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDLActionPerformed
        jog(-1,-1, 0);
    }//GEN-LAST:event_jButtonDLActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        jog(0,-1, 0);
    }//GEN-LAST:event_jButtonDActionPerformed

    private void jButtonDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDRActionPerformed
        jog(1,-1, 0);
    }//GEN-LAST:event_jButtonDRActionPerformed

    private void jCheckBoxShowLaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowLaserActionPerformed
        if ( grbl.isConnected()) {
            if ( jCheckBoxShowLaser.isSelected())
                grbl.pushCmd("G1F100M3S1");
            else
                grbl.pushCmd("G0");
            grbl.pushCmd("$G");
        }
    }//GEN-LAST:event_jCheckBoxShowLaserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ( grbl.isConnected()) grbl.jogCancel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBottomActionPerformed
        jog( 0, 0, -1);
    }//GEN-LAST:event_jButtonBottomActionPerformed

    private void jButtonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTopActionPerformed
        jog( 0, 0, 1);
    }//GEN-LAST:event_jButtonTopActionPerformed

    private void jTextFieldMyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMyActionPerformed

    private void jButtonZ0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZ0ActionPerformed
        grbl.pushCmd("G10L20P1Z0");
    }//GEN-LAST:event_jButtonZ0ActionPerformed

    private void jTextFieldWyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWyActionPerformed
        try {
            double d = Double.valueOf( jTextFieldWz.getText());
            grbl.pushCmd("G10L20Y"+GWord.roundForGCODE(d));         
        } catch ( NumberFormatException e) { }
    }//GEN-LAST:event_jTextFieldWyActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        grbl.goHome();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonX0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX0ActionPerformed
        grbl.pushCmd("G10L20P1X0");
    }//GEN-LAST:event_jButtonX0ActionPerformed

    private void jButtonY0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonY0ActionPerformed
        grbl.pushCmd("G10L20P1Y0");// TODO add your handling code here:
    }//GEN-LAST:event_jButtonY0ActionPerformed

    private void jButtonW0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonW0ActionPerformed
        grbl.pushCmd("G10L20P1X0Y0Z0");
    }//GEN-LAST:event_jButtonW0ActionPerformed

    private void jTextFieldWzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWzActionPerformed
        try {
            double d = Double.valueOf( jTextFieldWz.getText());
            grbl.pushCmd("G10L20Z"+GWord.roundForGCODE(d));         
        } catch ( NumberFormatException e) { }
    }//GEN-LAST:event_jTextFieldWzActionPerformed

    private void jTextFieldWxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWxActionPerformed
        try {
            double d = Double.valueOf( jTextFieldWz.getText());
            grbl.pushCmd("G10L20X"+GWord.roundForGCODE(d));         
        } catch ( NumberFormatException e) { }
    }//GEN-LAST:event_jTextFieldWxActionPerformed

    private void jButtonHoldResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHoldResumeActionPerformed
        if ( grbl.getState() != GRBLControler.GRBL_STATE_HOLD) grbl.hold();
        else grbl.cycleStartResume();
    }//GEN-LAST:event_jButtonHoldResumeActionPerformed

    private void jog(int x, int y, int z) {
        Object o = jComboBoxDistance.getEditor().getEditorComponent();
        if ( o instanceof JTextField) {
            double d = Double.valueOf(((JTextField) o).getText());
            grbl.jog(d * x, d * y, d * z, 5000, true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced serialReader Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JJoGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JJoGFrame(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBottom;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonDL;
    private javax.swing.JButton jButtonDR;
    private javax.swing.JButton jButtonDiv10;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonHoldResume;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMul10;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonTop;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonUL;
    private javax.swing.JButton jButtonUR;
    private javax.swing.JButton jButtonW0;
    private javax.swing.JButton jButtonX0;
    private javax.swing.JButton jButtonY0;
    private javax.swing.JButton jButtonZ0;
    private javax.swing.JCheckBox jCheckBoxShowLaser;
    private javax.swing.JComboBox<String> jComboBoxDistance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCoordValues;
    private javax.swing.JPanel jPanelJogButtons;
    private javax.swing.JPanel jPanelPrecision;
    private javax.swing.JTextField jTextFieldMx;
    private javax.swing.JTextField jTextFieldMy;
    private javax.swing.JTextField jTextFieldMz;
    private javax.swing.JTextField jTextFieldWx;
    private javax.swing.JTextField jTextFieldWy;
    private javax.swing.JTextField jTextFieldWz;
    // End of variables declaration//GEN-END:variables
}
