/*
 * Copyright (C) 2019 Clément GERARDIN @ Marseille.fr
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gcodeeditor.gui;

import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Clément
 */
public class SetCursorToPanel extends javax.swing.JPanel {

    public enum Choice { CANCEL, ORIGIN, CURSOR, SEL_UL, SEL_U, SEL_UR, SEL_L, SEL_C, SEL_R, SEL_DL, SEL_D, SEL_DR };
    
    Frame parent;
    JDialog dialog;
    Choice  validated;
    public double x, y;
    
    /**
     * Creates new form SetCursorToPanel
     */
    public SetCursorToPanel(Frame parent) {
        initComponents();
        buttonGroupFrom.add(jRadioButtonOrigin);
        buttonGroupFrom.add(jRadioButton2DCursor);
        buttonGroupFromSelection.add( jRadioButtonUL);
        buttonGroupFromSelection.add( jRadioButtonU);
        buttonGroupFromSelection.add( jRadioButtonUR);
        buttonGroupFromSelection.add( jRadioButtonL);
        buttonGroupFromSelection.add( jRadioButtonC);
        buttonGroupFromSelection.add( jRadioButtonR);
        buttonGroupFromSelection.add( jRadioButtonDL);
        buttonGroupFromSelection.add( jRadioButtonD);
        buttonGroupFromSelection.add( jRadioButtonDR);
        this.parent = parent;
    }
    
    public Choice showDialog()
    {
        if (dialog == null) {
            dialog = new JDialog(parent, "Set cursor position", true);
            dialog.getContentPane().add(this);
            dialog.pack();
            
        }
        dialog.setLocationRelativeTo(parent);
        dialog.setVisible(true);
        return validated;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFrom = new javax.swing.ButtonGroup();
        buttonGroupFromSelection = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelFixed = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonOrigin = new javax.swing.JRadioButton();
        jRadioButton2DCursor = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldY = new javax.swing.JTextField();
        jPanelSelection = new javax.swing.JPanel();
        jRadioButtonUL = new javax.swing.JRadioButton();
        jRadioButtonU = new javax.swing.JRadioButton();
        jRadioButtonUR = new javax.swing.JRadioButton();
        jRadioButtonL = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jRadioButtonR = new javax.swing.JRadioButton();
        jRadioButtonDL = new javax.swing.JRadioButton();
        jRadioButtonD = new javax.swing.JRadioButton();
        jRadioButtonDR = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonSet = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelFixed.setLayout(new java.awt.GridLayout(3, 0));

        jLabel1.setText("From");
        jPanelFixed.add(jLabel1);

        jRadioButtonOrigin.setSelected(true);
        jRadioButtonOrigin.setText("Origin");
        jPanelFixed.add(jRadioButtonOrigin);

        jRadioButton2DCursor.setText("2D Cursor");
        jPanelFixed.add(jRadioButton2DCursor);

        jLabel3.setText("X");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelFixed.add(jLabel3);

        jTextFieldX.setText("0");
        jPanelFixed.add(jTextFieldX);
        jPanelFixed.add(jLabel4);

        jLabel2.setText("Y");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelFixed.add(jLabel2);

        jTextFieldY.setText("0");
        jPanelFixed.add(jTextFieldY);

        jTabbedPane1.addTab("Fixed", jPanelFixed);

        jPanelSelection.setLayout(new java.awt.GridLayout(0, 3));

        jRadioButtonUL.setText("Up left");
        jPanelSelection.add(jRadioButtonUL);

        jRadioButtonU.setText("Up");
        jPanelSelection.add(jRadioButtonU);

        jRadioButtonUR.setText("Up right");
        jPanelSelection.add(jRadioButtonUR);

        jRadioButtonL.setText("Center Left");
        jPanelSelection.add(jRadioButtonL);

        jRadioButtonC.setSelected(true);
        jRadioButtonC.setText("Center");
        jPanelSelection.add(jRadioButtonC);

        jRadioButtonR.setText("Center right");
        jPanelSelection.add(jRadioButtonR);

        jRadioButtonDL.setText("Down left");
        jPanelSelection.add(jRadioButtonDL);

        jRadioButtonD.setText("Down");
        jPanelSelection.add(jRadioButtonD);

        jRadioButtonDR.setText("Down right");
        jPanelSelection.add(jRadioButtonDR);

        jTabbedPane1.addTab("To selection", jPanelSelection);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel);

        jButtonSet.setText("Set");
        jButtonSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSet);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetActionPerformed
        try {
            if ( jTabbedPane1.getSelectedComponent() == jPanelFixed) {
                x = Double.parseDouble(jTextFieldX.getText());
                y = Double.parseDouble(jTextFieldY.getText());
                if ( jRadioButtonOrigin.isSelected() ) {
                    validated = Choice.ORIGIN;
                } else 
                    validated = Choice.CURSOR;
            } else {
                if ( jRadioButtonUL.isSelected()) validated = Choice.SEL_UL;
                if ( jRadioButtonU.isSelected()) validated = Choice.SEL_U;
                if ( jRadioButtonUR.isSelected()) validated = Choice.SEL_UR;
                if ( jRadioButtonL.isSelected()) validated = Choice.SEL_L;
                if ( jRadioButtonC.isSelected()) validated = Choice.SEL_C;
                if ( jRadioButtonR.isSelected()) validated = Choice.SEL_R;
                if ( jRadioButtonDL.isSelected()) validated = Choice.SEL_DL;
                if ( jRadioButtonD.isSelected()) validated = Choice.SEL_D;
                if ( jRadioButtonDR.isSelected()) validated = Choice.SEL_DR;       
            }
            dialog.setVisible(false);
        } catch ( NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Numeric format error", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonSetActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        validated = Choice.CANCEL;
        dialog.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFrom;
    private javax.swing.ButtonGroup buttonGroupFromSelection;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFixed;
    private javax.swing.JPanel jPanelSelection;
    private javax.swing.JRadioButton jRadioButton2DCursor;
    private javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JRadioButton jRadioButtonD;
    private javax.swing.JRadioButton jRadioButtonDL;
    private javax.swing.JRadioButton jRadioButtonDR;
    private javax.swing.JRadioButton jRadioButtonL;
    private javax.swing.JRadioButton jRadioButtonOrigin;
    private javax.swing.JRadioButton jRadioButtonR;
    private javax.swing.JRadioButton jRadioButtonU;
    private javax.swing.JRadioButton jRadioButtonUL;
    private javax.swing.JRadioButton jRadioButtonUR;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
}
