/*
 * Copyright (C) 2023 clement
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gcodeeditor.gui.dialogs;

import javax.swing.JOptionPane;

/**
 * the panel to create new polygon
 * @author clement
 */
public class JPolygonPanel extends ManagedPanel {

    public int nbEdge;
    public double edgeLen, radius;
    public boolean clockwise, rotate;
    
    
    public JPolygonPanel() {
        super("new Polygon");
        initComponents();
    }
    
    @Override
    public boolean validateFields() {

            nbEdge = parseIntExpression(jTextFieldNbEdges, false);
                        
            edgeLen = parseExpression(jTextFieldEdgeLen, true);
            if ( edgeLen == Double.MIN_VALUE) edgeLen = -1;           
            
            radius = parseExpression(jTextFieldRadius, true );
            if ( radius == Double.NEGATIVE_INFINITY) radius = -1;
            
            clockwise = jCheckBoxClockwise.isSelected();
            rotate = jCheckBoxRotate.isSelected();
            
            if (((edgeLen < 0) && (radius < 0)) | ((edgeLen > 0) && (radius > 0))) {
                JOptionPane.showMessageDialog(dialog, "Must supply len or radius", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            else return ! (isNaN(edgeLen) || isNaN(radius) || (nbEdge == Integer.MAX_VALUE));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNbEdges = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxRotate = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEdgeLen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRadius = new javax.swing.JTextField();
        jCheckBoxClockwise = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout(0, 10));

        jLabel7.setText("Create a new polygon centered to 2DCursor");
        add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setText("Number of edges");
        jPanel1.add(jLabel1);

        jTextFieldNbEdges.setText("4");
        jPanel1.add(jTextFieldNbEdges);
        jPanel1.add(jLabel4);

        jCheckBoxRotate.setText("Rotate");
        jPanel1.add(jCheckBoxRotate);

        jLabel2.setText("Edges len");
        jPanel1.add(jLabel2);

        jTextFieldEdgeLen.setText("100");
        jPanel1.add(jTextFieldEdgeLen);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("or");
        jPanel1.add(jLabel8);
        jPanel1.add(jLabel9);

        jLabel3.setText("Radius from 2DCursor");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldRadius);

        jCheckBoxClockwise.setSelected(true);
        jCheckBoxClockwise.setText("Clockwise");
        jPanel1.add(jCheckBoxClockwise);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxClockwise;
    private javax.swing.JCheckBox jCheckBoxRotate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEdgeLen;
    private javax.swing.JTextField jTextFieldNbEdges;
    private javax.swing.JTextField jTextFieldRadius;
    // End of variables declaration//GEN-END:variables
}
