/*
 * Copyright (C) 2019 Clément Gérardin @ Marseille.fr
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gcodeeditor.gui.dialogs;

/**
 *
 * @author Clément
 */
public class JRotationPanel extends ManagedPanel {

    public double angle;
    public int copies;
    public boolean keepOriginal, keepOrientation;
    public boolean fromCenter;
    
    /**
     * Creates new form JRotationPanel
     */
    public JRotationPanel() {
        super("Rotate selection");
        initComponents();
        jRadioButtonO2D.setSelected(true);
    }
    
    
    @Override
    public boolean validateFields() {
        angle = containsValidNumber(jTextFieldAngle, false);
        copies = containsValidInteger(jTextFieldCopies, false);
        keepOriginal = jCheckBoxOriginal.isSelected();
        fromCenter = jRadioButtonOCenter.isSelected();
        keepOrientation = jCheckBoxOrientation.isSelected() && jRadioButtonO2D.isSelected();
        
        return ! (isNaN(angle) || isNaN(copies));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupOrigine = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonO2D = new javax.swing.JRadioButton();
        jRadioButtonOCenter = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCopies = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAngle = new javax.swing.JTextField();
        jCheckBoxOriginal = new javax.swing.JCheckBox();
        jCheckBoxOrientation = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Origin"));

        buttonGroupOrigine.add(jRadioButtonO2D);
        jRadioButtonO2D.setSelected(true);
        jRadioButtonO2D.setText("2D cursor");
        jRadioButtonO2D.setToolTipText("Turn around 2D Cursor");
        jRadioButtonO2D.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonO2DStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButtonO2D);

        buttonGroupOrigine.add(jRadioButtonOCenter);
        jRadioButtonOCenter.setText("Center");
        jRadioButtonOCenter.setToolTipText("turn around center of path");
        jPanel1.add(jRadioButtonOCenter);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        add(jPanel1, gridBagConstraints);

        jLabel2.setText("Count");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(jLabel2, gridBagConstraints);

        jTextFieldCopies.setColumns(6);
        jTextFieldCopies.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 0);
        add(jTextFieldCopies, gridBagConstraints);

        jLabel1.setText("Angle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(jLabel1, gridBagConstraints);

        jTextFieldAngle.setColumns(6);
        jTextFieldAngle.setToolTipText("Angle in degre (can be negative)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 0);
        add(jTextFieldAngle, gridBagConstraints);

        jCheckBoxOriginal.setText("Keep original");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        add(jCheckBoxOriginal, gridBagConstraints);

        jCheckBoxOrientation.setText("Keep orientation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(jCheckBoxOrientation, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonO2DStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonO2DStateChanged
        jCheckBoxOrientation.setEnabled(jRadioButtonO2D.isSelected());
    }//GEN-LAST:event_jRadioButtonO2DStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOrigine;
    private javax.swing.JCheckBox jCheckBoxOrientation;
    private javax.swing.JCheckBox jCheckBoxOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonO2D;
    private javax.swing.JRadioButton jRadioButtonOCenter;
    private javax.swing.JTextField jTextFieldAngle;
    private javax.swing.JTextField jTextFieldCopies;
    // End of variables declaration//GEN-END:variables
}
